###############################################
# Run GitHub's Super Linter against code base #
###############################################
---
name: GitHub's Super Linter
on: push
jobs:
  run-linters:
    name: GitHub's Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@master
      - name: Run GitHub Super Linter
        uses: github/super-linter@main
        env:
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CLANG_FORMAT: false
          VALIDATE_JAVASCRIPT_STANDARD: false
          VALIDATE_PYTHON_FLAKE8: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
[![GitHub's Super Linter](https://github.com/Yiyun-Qin/<REPOSITORY>/workflows/GitHub's%20Super%20Linter/badge.svg)](https://github.com/Yiyun-Qin/<REPOSITORY>/actions)
